name: "CI power"
on:
  pull_request:
  push:
jobs:
  shellcheck:
    runs-on: ubuntu-22.04-ppc64le
    steps:
    - uses: actions/checkout@v3
    - run: shellcheck tests/*.sh
  nix:
    runs-on: ubuntu-22.04-ppc64le
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v25
    - run: nix-build -A hydraJobs.release
  ubuntu:
    runs-on: ubuntu-22.04-ppc64le
    steps:
    - uses: actions/checkout@v3
    - name: get toolchain version
      run: |
        c++ --version
        ld --version
        autoconf --version
    - run: |
        ./bootstrap.sh
        mkdir build && cd build
        ../configure --with-asan --with-ubsan
        make -j$(nproc) check
